# Generated by Django 5.2.8 on 2025-11-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='cart',
        ),
        migrations.AddField(
            model_name='feature',
            name='cart',
            field=models.ManyToManyField(related_name='features', to='admin_side.cartfeature'),
        ),
    ]
