# Generated by Django 5.2.8 on 2025-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_remove_feature_cart_feature_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpackage',
            options={},
        ),
        migrations.RemoveField(
            model_name='userpackage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='userpackage',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='userpackage',
            name='start_date',
        ),
        migrations.AddField(
            model_name='package',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='status',
            field=models.CharField(default='incomplete', max_length=50),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
