# Generated by Django 5.2.8 on 2025-12-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_alter_userpackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stripe_price_id_dkk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
