# Generated by Django 5.2.8 on 2025-11-11 10:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True)),
                ('role', models.SmallIntegerField(choices=[(1, 'User'), (2, 'Admin')], default=1)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default='user/profile/default.png', null=True, upload_to='user/profile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', '.jpg', 'jpeg', 'png', 'webp'])], verbose_name='Profile Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserWhitelistToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('access_token_fingerprint', models.TextField()),
                ('refresh_token_fingerprint', models.TextField()),
                ('login_info', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tokens', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
