# Generated by Django 5.2.8 on 2025-12-01 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_user_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERankingKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('keyword', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('block_type', models.CharField(blank=True, max_length=50, null=True)),
                ('block_position', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('prev_pos', models.IntegerField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('cpc', models.FloatField(blank=True, null=True)),
                ('competition', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('total_sites', models.IntegerField(blank=True, null=True)),
                ('traffic', models.IntegerField(blank=True, null=True)),
                ('traffic_percent', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
