# Generated by Django 5.2.8 on 2025-12-02 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_similarkeyword'),
        ('user', '0004_user_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('keyword', models.CharField(max_length=255)),
                ('cpc', models.FloatField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('competition', models.FloatField(default=0)),
                ('serp_features', models.JSONField(default=list)),
                ('intents', models.JSONField(default=list)),
                ('history_trend', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
