# Generated by Django 5.2.8 on 2025-12-02 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_domainhistory'),
        ('user', '0004_user_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('total_warnings', models.IntegerField(blank=True, null=True)),
                ('total_errors', models.IntegerField(blank=True, null=True)),
                ('total_passed', models.IntegerField(blank=True, null=True)),
                ('total_notices', models.IntegerField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('dp_dt', models.IntegerField(blank=True, null=True)),
                ('dp_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('dp_domains', models.CharField(blank=True, max_length=255, null=True)),
                ('dp_expdate', models.CharField(blank=True, max_length=50, null=True)),
                ('dp_updated', models.CharField(blank=True, max_length=50, null=True)),
                ('dp_backlinks', models.CharField(blank=True, max_length=50, null=True)),
                ('dp_all_checked', models.BooleanField(default=False)),
                ('dp_index_google', models.CharField(blank=True, max_length=50, null=True)),
                ('score_percent', models.IntegerField(blank=True, null=True)),
                ('weighted_score_percent', models.IntegerField(blank=True, null=True)),
                ('screenshot', models.TextField(blank=True, null=True)),
                ('audit_time', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('chromeux_mobile', models.JSONField(blank=True, null=True)),
                ('chromeux_desktop', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
