# Generated by Django 5.2.8 on 2025-12-08 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_auditreport'),
        ('user', '0004_user_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAuditLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('link_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_noindex', models.CharField(blank=True, max_length=10, null=True)),
                ('nofollow', models.CharField(blank=True, max_length=10, null=True)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('anchor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('anchor', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
