# Generated by Django 5.2.8 on 2025-12-08 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_seoauditlink'),
        ('user', '0004_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoauditlink',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SEOAuditIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('issue_code', models.CharField(max_length=50)),
                ('issue_type', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('snippet_value', models.JSONField()),
                ('time_check', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
