# Generated by Django 5.2.8 on 2025-12-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_alter_seoauditlink_alt_seoauditissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoauditissue',
            name='inlinks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seoauditissue',
            name='issues_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seoauditissue',
            name='num_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seoauditissue',
            name='redirect',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seoauditissue',
            name='refpages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seoauditissue',
            name='traffic_forecast',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seoauditissue',
            name='warnings_count',
            field=models.IntegerField(default=0),
        ),
    ]
